### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by DavidHernandez**

### CODE REVIEW

**Comment by DavidHernandez** [comment]
Como traducimos lo siguiente:
- vigilancia ciudadana.

**Comment by javipe** [comment]
Hola @DavidHernandez, te voy poniendo por aquí algunos comentarios a la traducción de la web de PW:
- En la  Home, creo que en lugar de "In our hands" es más correcto "At hand" o "Current topics".
- En el título de ColeSeguro, cambiar "The right for education" por "The right to...". En esa misma sección sugiero cambiar "Despite the different plans to come back to the classrooms" por "Despite the different back to school plans..." y cambiar "course" por "school year".
- Bajo el nombre de "Coherence" sugiero poner "Policies that live up to the challenges of our era".

**Comment by javipe** [comment]
@DavidHernandez: para el apartado About Us, te paso el mismo texto, pero según la traducción que tenemos en nuestro dossier de PW en inglés:

Political Watch is an independent organisation that, through the development of civic technologies, advocacy and research, fights for a more fair, democratic and sustainable society.

We believe in:
The potential of an active, conscious and demanding citizenship.
The need to subject power to citizen surveillance.
The value of a capable and independent media.

We contribute by:
Providing open access to information through the development of civic technologies.
Promoting citizen surveillance and participation and public accountability.  
Generating content and spaces to stimulate an informed public debate.

**Comment by javipe** [comment]
Aún en la página de About us, tres comentarios más:
- En el párrafo sobre la Fundación Salvador Soler, al final pondría "since 2010" y no "since year 2010".
- Mi cita la pondría así: "Not committing decisively to working for an equitable and sustainable development is no longer an option. We need an active, conscious and demanding citizenship and a political class which is subject to citizen surveillance".
- En el texto de Transparency: "We don't want to demand what we don't do. For that reason we commit to be totally transparent and to make our accounts public. So you can see our financing sources, who do we work with and how do we invest or budget".

**Pull request merged**
